#!/usr/bin/env python3
"""
Dump the live Supabase schema to sql/schema.sql using catalog reads only.

Why this exists instead of `supabase db dump`: that command requires Docker, which
is not installed on the Mac Mini. This reconstructs the same information by asking
Postgres to emit its own DDL (pg_get_indexdef / pg_get_constraintdef /
pg_get_functiondef / pg_get_triggerdef / pg_get_viewdef) plus a hand-built
CREATE TABLE from information_schema.

Read-only. Touches system catalogs only, never table contents — this is NOT the
bulk-read pattern that caused the 2026-08-13 outage.

Usage: python3 scripts/dump-schema.py
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "sql" / "schema.sql"


def q(sql: str):
    """Run one query through the Supabase CLI and return its rows."""
    p = subprocess.run(
        ["npx", "supabase", "db", "query", "--linked", sql],
        cwd=ROOT, capture_output=True, text=True,
    )
    out = p.stdout
    start = out.find("{")
    if start == -1:
        sys.exit(f"no JSON in response:\n{out}\n{p.stderr}")
    data = json.loads(out[start:])
    if data.get("_tag") == "Error":
        sys.exit(f"query failed: {data['error']['message']}\n--- SQL ---\n{sql}")
    return data.get("rows", [])


def section(title: str) -> str:
    bar = "-" * 74
    return f"\n--\n-- {title}\n--{bar[:len(bar)]}\n"


parts = [
    "-- WRotate — production schema snapshot",
    "-- Generated by scripts/dump-schema.py from the live database (catalog reads only).",
    "-- This file is the authoritative record of the schema: migration history diverged",
    "-- from the repo on 2026-05-14 and most objects exist only in the live DB.",
    "-- See audit-results/2026-08-13-reliability-audit.md R7.",
    "--",
    "-- Regenerate after any `supabase db query --linked` schema change:",
    "--   python3 scripts/dump-schema.py",
    "",
]

# ── extensions ───────────────────────────────────────────────────────────────
parts.append(section("Extensions"))
for r in q("""SELECT e.extname, n.nspname
              FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace
              ORDER BY 1;"""):
    parts.append(f'CREATE EXTENSION IF NOT EXISTS "{r["extname"]}" WITH SCHEMA {r["nspname"]};')

# ── enums / composite types ──────────────────────────────────────────────────
rows = q("""SELECT t.typname, string_agg(quote_literal(e.enumlabel), ', ' ORDER BY e.enumsortorder) AS labels
            FROM pg_type t JOIN pg_enum e ON e.enumtypid=t.oid
            JOIN pg_namespace n ON n.oid=t.typnamespace
            WHERE n.nspname='public' GROUP BY 1 ORDER BY 1;""")
if rows:
    parts.append(section("Types"))
    for r in rows:
        parts.append(f'CREATE TYPE public.{r["typname"]} AS ENUM ({r["labels"]});')

# ── tables ───────────────────────────────────────────────────────────────────
parts.append(section("Tables"))
tables = [r["tablename"] for r in q(
    "SELECT tablename FROM pg_tables WHERE schemaname='public' ORDER BY tablename;")]

cols = q("""SELECT table_name, column_name, data_type, udt_name, character_maximum_length,
                   numeric_precision, numeric_scale, is_nullable, column_default, ordinal_position
            FROM information_schema.columns WHERE table_schema='public'
            ORDER BY table_name, ordinal_position;""")
by_table = {}
for c in cols:
    by_table.setdefault(c["table_name"], []).append(c)


def coltype(c):
    dt, udt = c["data_type"], c["udt_name"]
    if dt == "ARRAY":
        return f"{udt.lstrip('_')}[]"
    if dt == "USER-DEFINED":
        return f"public.{udt}"
    if dt == "character varying" and c["character_maximum_length"]:
        return f'character varying({c["character_maximum_length"]})'
    if dt == "numeric" and c["numeric_precision"]:
        return f'numeric({c["numeric_precision"]},{c["numeric_scale"] or 0})'
    return dt


for t in tables:
    lines = []
    for c in by_table.get(t, []):
        s = f'    {c["column_name"]} {coltype(c)}'
        if c["column_default"] is not None:
            s += f' DEFAULT {c["column_default"]}'
        if c["is_nullable"] == "NO":
            s += " NOT NULL"
        lines.append(s)
    parts.append(f"CREATE TABLE IF NOT EXISTS public.{t} (\n" + ",\n".join(lines) + "\n);")

# ── constraints ──────────────────────────────────────────────────────────────
parts.append(section("Constraints"))
for r in q("""SELECT c.conrelid::regclass::text AS tbl, c.conname, pg_get_constraintdef(c.oid) AS def,
                     CASE c.contype WHEN 'p' THEN 1 WHEN 'u' THEN 2 WHEN 'c' THEN 3 ELSE 4 END AS ord
              FROM pg_constraint c
              WHERE c.connamespace='public'::regnamespace AND c.contype IN ('p','u','c','f')
              ORDER BY ord, 1, 2;"""):
    parts.append(
        f'ALTER TABLE public.{r["tbl"].split(".")[-1]} '
        f'ADD CONSTRAINT {r["conname"]} {r["def"]};')

# ── indexes ──────────────────────────────────────────────────────────────────
parts.append(section("Indexes"))
for r in q("""SELECT indexdef FROM pg_indexes WHERE schemaname='public'
              AND indexname NOT IN (SELECT conname FROM pg_constraint WHERE connamespace='public'::regnamespace)
              ORDER BY tablename, indexname;"""):
    parts.append(r["indexdef"] + ";")

# ── functions ────────────────────────────────────────────────────────────────
parts.append(section("Functions"))
for r in q("""SELECT pg_get_functiondef(p.oid) AS def
              FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
              WHERE n.nspname='public' AND p.prokind IN ('f','p')
              ORDER BY p.proname;"""):
    parts.append(r["def"].rstrip() + ";")

# ── views ────────────────────────────────────────────────────────────────────
rows = q("""SELECT viewname, pg_get_viewdef(('public.'||quote_ident(viewname))::regclass, true) AS def
            FROM pg_views WHERE schemaname='public' ORDER BY viewname;""")
if rows:
    parts.append(section("Views"))
    for r in rows:
        parts.append(f'CREATE OR REPLACE VIEW public.{r["viewname"]} AS\n{r["def"].rstrip()}')

# ── triggers ─────────────────────────────────────────────────────────────────
parts.append(section("Triggers"))
for r in q("""SELECT pg_get_triggerdef(t.oid) AS def
              FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid
              JOIN pg_namespace n ON n.oid=c.relnamespace
              WHERE n.nspname='public' AND NOT t.tgisinternal
              ORDER BY c.relname, t.tgname;"""):
    parts.append(r["def"] + ";")

# ── RLS ──────────────────────────────────────────────────────────────────────
parts.append(section("Row Level Security"))
for r in q("""SELECT c.relname FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
              WHERE n.nspname='public' AND c.relkind='r' AND c.relrowsecurity
              ORDER BY 1;"""):
    parts.append(f'ALTER TABLE public.{r["relname"]} ENABLE ROW LEVEL SECURITY;')

parts.append(section("Policies"))
for r in q("""SELECT format('CREATE POLICY %I ON public.%I AS %s FOR %s TO %s%s%s;',
                     policyname, tablename, permissive, cmd, array_to_string(roles, ', '),
                     CASE WHEN qual IS NOT NULL THEN E'\n  USING (' || qual || ')' ELSE '' END,
                     CASE WHEN with_check IS NOT NULL THEN E'\n  WITH CHECK (' || with_check || ')' ELSE '' END
                   ) AS def
              FROM pg_policies WHERE schemaname='public'
              ORDER BY tablename, policyname;"""):
    parts.append(r["def"])

# ── grants (column-level included: relevant to profile privacy) ──────────────
parts.append(section("Grants"))
for r in q("""SELECT DISTINCT format('GRANT %s ON public.%I TO %I;', privilege_type, table_name, grantee) AS def
              FROM information_schema.role_table_grants
              WHERE table_schema='public' AND grantee IN ('anon','authenticated','service_role')
              ORDER BY 1;"""):
    parts.append(r["def"])

rows = q("""SELECT DISTINCT format('GRANT %s (%I) ON public.%I TO %I;',
                   privilege_type, column_name, table_name, grantee) AS def
            FROM information_schema.column_privileges
            WHERE table_schema='public' AND grantee IN ('anon','authenticated')
            ORDER BY 1;""")
if rows:
    parts.append("\n-- Column-level grants")
    for r in rows:
        parts.append(r["def"])

OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size:,} bytes, {len(OUT.read_text().splitlines()):,} lines)")
