-- Convert all demo_readonly_* write policies from PERMISSIVE to RESTRICTIVE.
-- Permissive demo_readonly policies OR'd with ownership policies, granting
-- writes to every non-demo authenticated user (broken access control).
-- RESTRICTIVE makes them AND with ownership: demo blocked, others follow ownership.
-- See audit-results/2026-05-31-security-audit.md

BEGIN;
DROP POLICY "demo_readonly_club_invites_delete" ON club_invites;
CREATE POLICY "demo_readonly_club_invites_delete" ON club_invites AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_club_invites_insert" ON club_invites;
CREATE POLICY "demo_readonly_club_invites_insert" ON club_invites AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_club_join_requests_delete" ON club_join_requests;
CREATE POLICY "demo_readonly_club_join_requests_delete" ON club_join_requests AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_club_join_requests_insert" ON club_join_requests;
CREATE POLICY "demo_readonly_club_join_requests_insert" ON club_join_requests AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_club_members_delete" ON club_members;
CREATE POLICY "demo_readonly_club_members_delete" ON club_members AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_club_members_insert" ON club_members;
CREATE POLICY "demo_readonly_club_members_insert" ON club_members AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_clubs_delete" ON clubs;
CREATE POLICY "demo_readonly_clubs_delete" ON clubs AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_clubs_insert" ON clubs;
CREATE POLICY "demo_readonly_clubs_insert" ON clubs AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_clubs_update" ON clubs;
CREATE POLICY "demo_readonly_clubs_update" ON clubs AS RESTRICTIVE FOR UPDATE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_comment_likes_delete" ON comment_likes;
CREATE POLICY "demo_readonly_comment_likes_delete" ON comment_likes AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_comment_likes_insert" ON comment_likes;
CREATE POLICY "demo_readonly_comment_likes_insert" ON comment_likes AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_comments_delete" ON comments;
CREATE POLICY "demo_readonly_comments_delete" ON comments AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_comments_insert" ON comments;
CREATE POLICY "demo_readonly_comments_insert" ON comments AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_content_reports_insert" ON content_reports;
CREATE POLICY "demo_readonly_content_reports_insert" ON content_reports AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_device_tokens_insert" ON device_tokens;
CREATE POLICY "demo_readonly_device_tokens_insert" ON device_tokens AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_device_tokens_update" ON device_tokens;
CREATE POLICY "demo_readonly_device_tokens_update" ON device_tokens AS RESTRICTIVE FOR UPDATE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_eula_insert" ON eula_acceptances;
CREATE POLICY "demo_readonly_eula_insert" ON eula_acceptances AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_feedback_insert" ON feedback;
CREATE POLICY "demo_readonly_feedback_insert" ON feedback AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_follow_requests_delete" ON follow_requests;
CREATE POLICY "demo_readonly_follow_requests_delete" ON follow_requests AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_follow_requests_insert" ON follow_requests;
CREATE POLICY "demo_readonly_follow_requests_insert" ON follow_requests AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_follows_delete" ON follows;
CREATE POLICY "demo_readonly_follows_delete" ON follows AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_follows_insert" ON follows;
CREATE POLICY "demo_readonly_follows_insert" ON follows AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_friend_requests_delete" ON friend_requests;
CREATE POLICY "demo_readonly_friend_requests_delete" ON friend_requests AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_friend_requests_insert" ON friend_requests;
CREATE POLICY "demo_readonly_friend_requests_insert" ON friend_requests AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_friend_requests_update" ON friend_requests;
CREATE POLICY "demo_readonly_friend_requests_update" ON friend_requests AS RESTRICTIVE FOR UPDATE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_likes_delete" ON likes;
CREATE POLICY "demo_readonly_likes_delete" ON likes AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_likes_insert" ON likes;
CREATE POLICY "demo_readonly_likes_insert" ON likes AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_logs_delete" ON logs;
CREATE POLICY "demo_readonly_logs_delete" ON logs AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_logs_insert" ON logs;
CREATE POLICY "demo_readonly_logs_insert" ON logs AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_logs_update" ON logs;
CREATE POLICY "demo_readonly_logs_update" ON logs AS RESTRICTIVE FOR UPDATE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_notifications_insert" ON notifications;
CREATE POLICY "demo_readonly_notifications_insert" ON notifications AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_notifications_update" ON notifications;
CREATE POLICY "demo_readonly_notifications_update" ON notifications AS RESTRICTIVE FOR UPDATE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_profiles_update" ON profiles;
CREATE POLICY "demo_readonly_profiles_update" ON profiles AS RESTRICTIVE FOR UPDATE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_tg_delete" ON timegrapher_results;
CREATE POLICY "demo_readonly_tg_delete" ON timegrapher_results AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_tg_insert" ON timegrapher_results;
CREATE POLICY "demo_readonly_tg_insert" ON timegrapher_results AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_tg_update" ON timegrapher_results;
CREATE POLICY "demo_readonly_tg_update" ON timegrapher_results AS RESTRICTIVE FOR UPDATE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_user_blocks_delete" ON user_blocks;
CREATE POLICY "demo_readonly_user_blocks_delete" ON user_blocks AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_user_blocks_insert" ON user_blocks;
CREATE POLICY "demo_readonly_user_blocks_insert" ON user_blocks AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_watches_delete" ON watches;
CREATE POLICY "demo_readonly_watches_delete" ON watches AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_watches_insert" ON watches;
CREATE POLICY "demo_readonly_watches_insert" ON watches AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_watches_update" ON watches;
CREATE POLICY "demo_readonly_watches_update" ON watches AS RESTRICTIVE FOR UPDATE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_wishlist_delete" ON wishlist;
CREATE POLICY "demo_readonly_wishlist_delete" ON wishlist AS RESTRICTIVE FOR DELETE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_wishlist_insert" ON wishlist;
CREATE POLICY "demo_readonly_wishlist_insert" ON wishlist AS RESTRICTIVE FOR INSERT WITH CHECK (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
DROP POLICY "demo_readonly_wishlist_update" ON wishlist;
CREATE POLICY "demo_readonly_wishlist_update" ON wishlist AS RESTRICTIVE FOR UPDATE USING (auth.uid() <> '73e4e48e-dbca-4b2e-82d2-35d5b39716d2'::uuid);
COMMIT;
