-- ROLLBACK for the S1/S2 privacy RLS fix (audit-results/2026-08-13-security-audit.md)
--
-- Captured from pg_policies on 2026-08-13 BEFORE any change was applied.
-- This is the exact prior state, generated by round-tripping pg_policies to DDL.
--
-- Apply with:
--   npx supabase db query --linked --file sql/2026-08-13-privacy-rls-rollback.sql
--
-- NOTE: DROP POLICY / CREATE POLICY touch access rules only — never row data.
-- Nothing here can lose a record. Policy changes also take effect immediately for
-- the next query: no deploy, no restart, and no `NOTIFY pgrst, 'reload schema'`
-- (that is only needed for new functions/columns; RLS is enforced by Postgres
-- itself at query time).

-- ─────────────────────────────────────────────────────────────────────────────
-- TIER 1 — BREAK-GLASS (single statement, ~1 second)
-- ─────────────────────────────────────────────────────────────────────────────
-- Permissive policies OR together — which is the very bug being fixed, and is
-- therefore also the fastest way to undo the fix. Adding ONE wide-open policy
-- instantly restores the prior effective read behaviour, because the prior
-- effective behaviour on profiles WAS `true`. Use if something user-facing
-- breaks and you need it working now; then come back and do Tier 2 properly.
--
--   CREATE POLICY emergency_profiles_read ON public.profiles
--     FOR SELECT TO public USING (true);
--
-- Same shape for watches / wishlist if those surfaces are the ones broken:
--   CREATE POLICY emergency_watches_read ON public.watches
--     FOR SELECT TO authenticated
--     USING ((user_id = auth.uid()) OR (watch_privacy IS DISTINCT FROM 'private'));
--
-- Remember to DROP the emergency_* policy once Tier 2 is applied, or it silently
-- re-opens the exact hole S1/S2 closed.

-- ─────────────────────────────────────────────────────────────────────────────
-- TIER 2 — EXACT RESTORE of the pre-change state
-- ─────────────────────────────────────────────────────────────────────────────

BEGIN;

-- Remove the replacement policy introduced by the fix (name it exactly as shipped).
DROP POLICY IF EXISTS profiles_select_respecting_privacy ON public.profiles;

-- Restore the four original profiles SELECT policies.
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles
  AS PERMISSIVE FOR SELECT TO public
  USING (true);

CREATE POLICY profiles_read ON public.profiles
  AS PERMISSIVE FOR SELECT TO public
  USING (true);

CREATE POLICY profiles_readable_by_authenticated ON public.profiles
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (true);

CREATE POLICY profiles_select ON public.profiles
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (true);

-- Restore the two original watches SELECT policies.
CREATE POLICY watches_feed_read ON public.watches
  AS PERMISSIVE FOR SELECT TO authenticated
  USING ((id IN ( SELECT logs.watch_id
     FROM logs
    WHERE (logs.visibility IS DISTINCT FROM 'private'::text))));

CREATE POLICY watches_public_read ON public.watches
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (((user_id = auth.uid()) OR (watch_privacy IS DISTINCT FROM 'private'::text)));

-- Restore the original wishlist SELECT policy.
CREATE POLICY "Non-private wishlist items readable by authenticated users" ON public.wishlist
  AS PERMISSIVE FOR SELECT TO authenticated
  USING (((user_id = auth.uid()) OR (wish_privacy IS DISTINCT FROM 'private'::text)));

COMMIT;

-- ─────────────────────────────────────────────────────────────────────────────
-- VERIFY the rollback landed (expect 7 rows)
-- ─────────────────────────────────────────────────────────────────────────────
-- SELECT tablename, policyname, permissive, cmd, roles::text
-- FROM pg_policies
-- WHERE schemaname='public' AND policyname IN (
--   'Public profiles are viewable by everyone','profiles_read',
--   'profiles_readable_by_authenticated','profiles_select',
--   'watches_public_read','watches_feed_read',
--   'Non-private wishlist items readable by authenticated users')
-- ORDER BY tablename, policyname;
